name: 'FE Build Image'
description: Build and push front-end image for deploy
inputs:
  registries:
    description: The list of registries URLs
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Docker registries info
      shell: bash
      id: registries
      run: |
        IMAGE_NAME=`basename ${{ github.repository }}`
        IMAGES=$(echo "${{ inputs.registries }}" | tr ',' ' ' |awk "{print \$1\"/\"\$2\"/$IMAGE_NAME\"}")
        echo $IMAGES
        echo "${{ inputs.registries }}"
