name: 'FE Build Image'
description: Build and push front-end image for deploy
inputs:
  registries:
    description: The list of registries URLs
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Docker registries info
      id: registries
      shell: bash
      run: |
        IMAGE_NAME=`basename ${{ github.repository }}`
        echo "images<<EOF" >> $GITHUB_OUTPUT
        echo "${{ inputs.registries }}" | while read line; do
          if [[ -z "$line" ]]; then
            break
          fi
          #echo "$line" | awk -F',' "{print \$1\"/\"\$2\"/$IMAGE_NAME\"}" >> $GITHUB_OUTPUT
          line=${line%,*}
          line=${line/,/\/}
          echo "$line" >> $GITHUB_OUTPUT
        done
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Login to the custom registry
      shell: bash
      run: |
        echo "${{ steps.registries.outputs.images}}"
