name: chart test
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  k3s:
    name: k3s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install k8s
        run: |
          https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: example tests
        run: |
          helm lint
