name: chart test
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  k3s:
    name: k3s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install k3s
        run: |

      - name: example tests
        run: |
          helm lint
