name: CI

on:
  workflow_dispatch:
  release:
    types: [published]
  # push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: 
            tower
          tags: |
            type=sha,evnet=branch
            type=sha,event=tag

      - run: echo ${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
