name: deploy proxy

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get project name
        run: cat configuration/${{ github.event.pull_request.body }}.yaml
