name: deploy proxy

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
      - run: echo ${{ steps.app-token.outputs.token }}
