name: deploy proxy

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
  workflow_run:
    workflows: ["login registry"]
    types:
      - completed
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name/app
          tags: |
            type=raw,value={{sha}}
      - run: echo ${{ steps.meta.outputs.version }}
