name: deploy proxy

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
  workflow_run:
    workflows: ["login registry"]
    types:
      - completed
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
           echo ${{ runner.temp }}
           ls ${{ runner.temp }}
