name: test issue trigger workflow

on:
  issues:
    types: [opened, reopened]

jobs:
  reverse_proxy:
    name: Reverse Proxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - run: echo "${{ github.event.issue.pull_request }}"
        
      - name: Generate the values configuration file
        run: echo "${{ github.event.issue.body }}" | grep -Ev '^###|^$|_No' > values.yaml

      - name: Get project name
        run: echo "PROJECT_NAME=$(cat values.yaml | yq '.project')" >> $GITHUB_ENV
        
      - name: Generate the reverse proxy configuration file
        run: |
          sed "s/example/${{ env.PROJECT_NAME }}/" example.yaml | \
            yq eval-all 'select(fileIndex==0).http.services.*.loadBalancer.servers =
            select(fileIndex==1).servers | select(fileIndex==0)' - values.yaml > configuration/${{ env.PROJECT_NAME }}.yaml
          
          if [[ -z $(yq '.middlewares' values.yaml) || $(yq '.middlewares' values.yaml) == null ]]; then
            echo "No additional middlewares are set, skip configuration"
          else
            yq eval-all --inplace 'select(fileIndex==0).http.middlewares +=
              select(fileIndex==1).middlewares | select(fileIndex==0)' configuration/${{ env.PROJECT_NAME }}.yaml values.yaml
              
            yq  '.middlewares | keys' values.yaml | \
              yq eval-all --inplace 'select(fileIndex==0).http.routers.*.middlewares +=
              select(fileIndex==1) | select(fileIndex==0)' configuration/${{ env.PROJECT_NAME }}.yaml -
          fi
          
      - name: Delete redundant files
        run: rm -f values.yaml
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "[REVERSE-PROXY]: ${{ env.PROJECT_NAME }} setting a reverse proxy"
          body: |
            ${{ env.PROJECT_NAME }}
