name: cs func

on: 
  push:
  
jobs:
 build:
   runs-on: ubuntu-latest
   env:
     my_str: |
       a,b,c,d \n
       a1,b1,c1,d1 \n
       a2,b2,c2,d2 \n
         
   steps:

     - id: repo-basename
       run: |
         echo $my_str | awk -F',' '{print $3","$4}'
         echo $my_str
       shell: bash
