name: cs func

on: 
  workflow_dispatch:
  
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - run: echo "REGISTRIES=ghrc.io,byzanteam,${{ github.repository_owner }},${{ secrets.github_token }}
        registry.aliyun.cn,jet,dev-man,${{ secrets.PASSWORD }}" >> $GITHUB_ENV
    - run: |
        for i in ${{ env.REGISTRIES.split(',') }}
        do
          echo "Value: $i"
        done
