name: cs func

on: 
  workflow_dispatch:
  
jobs:
 build:
   runs-on: ubuntu-latest
         
   steps:
     - name: Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: |
           ghcr.io/byzanteam/${{ env.RELEASE }}
         tags: |
           type=sha

     - run: echo ${{ steps.meta.outputs.version }}
