name: cs func

on: 
  push:
  
jobs:
 build:
   runs-on: ubuntu-latest
   env:
     my_str: a,b,c,d
       a1,b1,c1,d1
       a2,b2,c2,d2
         
   steps:

     - id: repo-basename
       run: |
         echo $my_str | awk -F',' '{print $3","$4}'
         echo $my_str
       shell: bash
