name: cs func

on: 
  workflow_dispatch:
  
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
      - name: Set up environment variables
        run: echo "MY_STRING=foo|bar|baz"

      - name: Use split to separate values
        run: |
          for i in ${{ env.MY_STRING.split('|') }}
          do
            echo "Value: $i"
          done
