name: cs func

on: 
  push:
  
jobs:
 build:
   runs-on: ubuntu-latest
         
   steps:
     #- uses: ykelit/test-chart@main
     #  with:
     #    registries: |-
     #      ghcr.io,byzanteam,${{ github.repository_owner }},${{ secrets.GITHUB_TOKEN }}
     #      registry.cn-hangzhou.aliyuncs.com,jet,dev-man,pass
     - run: |
         echo "::group::test"
         echo ${{ runner.name }}
         echo "::endgroup::"
         ehco "::group::test2"
         echo "1234"
         echo "::endgroup::"
