name: cs func

on: 
  workflow_dispatch:
  
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
      - name: Set up environment variables
        run: echo "MY_STRING=foo|bar|baz"

      - name: Use split to separate values
        run: |
          export MY_STRING_PARTS=(${MY_STRING//|/ })
          echo "The first part is ${MY_STRING_PARTS[0]}"
