name: login registry

on:
  release:
    types: [published]
  push:

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name/app
          tags: |
            type=raw,enable={{is_default_branch}},value=nightly
            type=sha
            type=semver,pattern={{version}}

      - run: echo "${{ steps.meta.outputs.version }}"
