name: login registry

on:
  release:
    types: [published]

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'Byzanteam/jet-actions'
        path: 'jet-actions'
        ref: 'bump-version'
        sparse-checkout: |
          denoified-actions/
