name: login registry

on: push

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
      # - name: login
      #   id: login-info
      #   uses: byzanteam/jet-actions/registry-login@main
      #   with:
      #     registry-info: ${{ secrets.ALIYUN_SKYLARK_REGISTRY }}
      # - run: docker pull registry.cn-chengdu.aliyuncs.com/yk-tools/nfs-provisioner:v4.0.8
      # - run: echo ${{ steps.login-info.outputs.hostname }}
      # - run: echo ${{ steps.login-info.outputs.namespace }}
      # - run: echo ${{ github.event }}
      - name: release name
        uses: byzanteam/jet-actions/uninstall-helm-release@feat/yangke/uninstall-helm-release
        with:
          k8s_token: ${{ secrets.TOKEN }}
          release_name: abc
