name: login registry

on: 
  pull_request:
    types: [opened, reopened, labeled]
  # push: 

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test_url=${{ github.event.pull_request.number }}.$(basename ${{ github.repository }}).apps.test.wrok" >> $GITHUB_OUTPUT
        id: url
      - uses: byzanteam/jet-actions/comment-pull-request@feat/yangke/comment-pr 
        with:
          message: |
            ${{ steps.url.outputs.test_url }}
            test2
