name: login registry

on: push

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: byzanteam/jet-actions/registry-login@feat/yangke/operate-login-info
        with:
          registry-info: ${{ secrets.ALIYUN_SKYLARK_REGISTRY }}
      - run: docker search registry.cn-chengdu.aliyuncs.com/yk-tools
