name: Test hello world
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test actions
        id: hello
        uses: byzanteam/jet-actions/registry-login@feat/yangke/operate-login-info
        with:
          registry-info: ${{ secrets.REGISTRY_INFO }}
      - name: Get the output time
        run: echo "The registry-hostname was ${{ steps.hello.outputs.registry-hostname }}"
